version: '3'

networks:
  cgpa_calculator_tier:
    driver: bridge

services:
  cgpa_calculator_web:
    container_name: cgpa_calculator
    build:
      context: .
      dockerfile: Dockerfile
    command: ./deployment/start-app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:20003:8001"
    networks:
      - cgpa_calculator_tier
